server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_demo
    username: root
    password: root
    # driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
    # 连接池最小空闲连接数
    minimum-idle: ${SPRING_DATASOURCE_MINIMUM_IDLE:20}
    # 连接池允许的最大连接数
    maximum-pool-size: ${SPRING_DATASOURCE_MAXIMUM_POOL_SIZE:200}
    # 等待连接池分配连接的最大时长（毫秒）
    connection-timeout: ${SPRING_DATASOURCE_CONNECTION_TIMEOUT:30000}
  redis:
    # 主机
    host: 127.0.0.1
    # 端口
    port: 6379
    # 连接密码
    password: ''
    # 默认DB
    pool:
    # 连接池最大连接数（使用负值表示没有限制）
    max-active: 8
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait: -1
    #连接池中的最大空闲连接
    max-idle: 8
    #连接池中的最小空闲连接
    min-idle: 0
    #连接超时时间（毫秒）
    timeout: 30000
    database: 1
  application:
    name: cloud-module-service
  # Spring Security Default user name and password
  security:
    user:
      name: Mycroft
      password: actuator
      roles: ACTUATOR_ADMIN

# mybatis的mapper书写路径
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    # 日志实现类
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    default-statement-timeout: ${MYBATIS_DEFAULT_STATEMENT_TIMEOUT:120}
    call-setters-on-nulls: true
  log:
    intact: true


logging:
  level:
    com.example: ${LOG_LEVEL:debug}
#  file:
#    # 配置日志输出文件的路径及文件名
#    name: C:\Users\Summer\Desktop\springboot_demo.txt
rocketmq:
  name-server: 127.0.0.1:9876
  # 生产者
  producer:
    group: springboot_demo_group
    send-message-timeout: 3000

mycroft:
  config:
    observer:
    name: ${OBSERVER_NAME:MYCROFT}
    ip: ${IP_ADDRESS:127.0.0.1}
eureka:
  instance:
    instance-id: cloud-module-service
    # 心跳发送时间间隔
    lease-renewal-interval-in-seconds: 1
    # eureka服务端等待时间,超时踢出
    lease-expiration-duration-in-seconds: 2
  client:
    register-with-eureka: true #把自己注册进eureka
    #是否从eureka抓取已有的注册信息,默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka1.com:8000/eureka, http://eureka2.com:8002/eureka
# 用来展示项目的基本信息
info:
  author.name: Mycroft
  app.name: spring-cloud-module1
  server.port: ${server.port}
  application.name: ${spring.application.name}

# actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: '*'

# ribbon(openfeign)设置openfeign超时时间
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
