server:
  port: 8850

spring:
  application:
    name: cloud-alibaba-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: '*'