server:
  port: 8500

spring:
  application:
    name: cloud-module-config
  cloud:
    config:
      server:
        git:
          uri: git@gitee.com:imsummerwind/spring-cloud-config.git
          ## 搜索目录
          search-paths:
            - spring-cloud-config
      ## 读取分支
      label: develop

eureka:
  instance:
    hostname: cloud-module-config
  client:
    service-url:
      defaultZone: http://eureka1.com:8000/eureka