server:
  port: 8002

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_demo
    username: root
    password: root
    # driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
    # 连接池最小空闲连接数
    minimum-idle: ${SPRING_DATASOURCE_MINIMUM_IDLE:20}
    # 连接池允许的最大连接数
    maximum-pool-size: ${SPRING_DATASOURCE_MAXIMUM_POOL_SIZE:200}
    # 等待连接池分配连接的最大时长（毫秒）
    connection-timeout: ${SPRING_DATASOURCE_CONNECTION_TIMEOUT:30000}
  redis:
    # 主机
    host: 127.0.0.1
    # 端口
    port: 6379
    # 连接密码
    password: ''
    # 默认DB
    pool:
    # 连接池最大连接数（使用负值表示没有限制）
    max-active: 8
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait: -1
    #连接池中的最大空闲连接
    max-idle: 8
    #连接池中的最小空闲连接
    min-idle: 0
    #连接超时时间（毫秒）
    timeout: 30000
    database: 1
  application:
    name: spring-cloud-module2


# mybatis的mapper书写路径
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    # 日志实现类
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    default-statement-timeout: ${MYBATIS_DEFAULT_STATEMENT_TIMEOUT:120}
    call-setters-on-nulls: true
  log:
    intact: true


#logging:
#  level:
#    # 配置目录下的日志输出级别
#    org.apache.ibatis: ${LOG_LEVEL:debug}
#    com.example.springbootdemo: ${LOG_LEVEL:debug}
#    org.apache.catalina: ${LOG_LEVEL:debug}
#  file:
#    # 配置日志输出文件的路径及文件名
#    name: C:\Users\Summer\Desktop\springboot_demo.txt

logging:
  level:
    com.example: ${LOG_LEVEL:debug}

rocketmq:
  name-server: 127.0.0.1:9876
  # 生产者
  producer:
    group: springboot_demo_group
    send-message-timeout: 3000

mycroft:
  config:
    observer:
    name: ${OBSERVER_NAME:MYCROFT}
    ip: ${IP_ADDRESS:127.0.0.1}
eureka:
  client:
    service-url:
      defaultZone: http://eureka1.com:8000/eureka
  instance:
    hostname: eureka2.com
