server:
  port: 9000

spring:
  main:
    web-application-type: reactive
  application:
    name: cloud-module-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由的功能,利用微服务名进行路由

      routes:
        - id: service-1               #路由的ID,没有固定规则,但要求唯一
          # uri: http://127.0.0.1:8001  #匹配后提供服务的路由地址
          uri: lb://SPRING-CLOUD-MODULE1 #匹配后提供服务的路由地址
          predicates:
            - Path=/module1/**        #断言,路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-module-gateway
  client:
    service-url:
      defaultZone: http://eureka1.com:8000/eureka
